### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by d4rky-pl** [xouabita/razzle-heroku#1]
Default node version on Heroku is 6.11.3, unfortunately it does not include `Object.entries`.
Upgrading node version in package.json solves the problem but it might be confusing to newcomers.

**Comment by xouabita** [comment]
Thank you for the report. It should be fixed with [this commit](https://github.com/xouabita/razzle-heroku/commit/847f7155702fda33967a3e24f19ade9fdefb8f8a).
Please upgrade your package 😃
